# Generated by Django 4.0.6 on 2022-07-27 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0003_person_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color', to='coreapi.color'),
        ),
    ]
